config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index
    root to: 'restaurants#index'

  resources :restaurants, only: [:index, :show, :new, :create] do
    resources :reviews, only: [:create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy

  validates :name, :address, :category, presence: true
  validates :category, inclusion: { in: %w[chinese italian japanese french belgian] }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant

  validates :content, presence: true
  validates :rating,
            presence: true,
            numericality: { only_integer: true, greater_than_or_equal_to: 0, less_than_or_equal_to: 5 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    @restaurants = Restaurant.all
  end

  def show
    @restaurant = Restaurant.find(params[:id])
    @review     = Review.new
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to @restaurant
    else
      render :new
    end
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :category)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def create
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review     = @restaurant.reviews.build(review_params)
    if @review.save
      redirect_to @restaurant
    else
      @restaurants = Restaurant.all
      render 'restaurants/show'
    end
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>


    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
      crossorigin="anonymous"
    />
  </head>

  <body>

    <nav class="navbar navbar-expand-lg navbar-light bg-light mb-4">
      <div class="container">
        <%= link_to "RailsYelpMvp", root_path, class: "navbar-brand" %>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item">
              <%= link_to "All Restaurants", restaurants_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "New Restaurant", new_restaurant_path, class: "nav-link" %>
            </li>
          </ul>
        </div>
      </div>
    </nav>


    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/restaurants/_form.html.erb
<%= simple_form_for(restaurant) do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :phone_number %>
  <%= f.input :category, collection: %w[chinese italian japanese french belgian], prompt: "Choose Category" %>
  <%= f.button :submit, class: "btn btn-success mt-3" %>
<% end %>

app/views/restaurants/index.html.erb
<h1>All Restaurants</h1>
<div class="row">
  <% @restaurants.each do |r| %>
    <div class="col-md-4 mb-3">
      <div class="card h-100">
        <div class="card-body">
          <h5 class="card-title"><%= r.name %></h5>
          <p class="card-text text-capitalize"><%= r.category %></p>
          <%= link_to "Details", restaurant_path(r), class: "btn btn-primary" %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/restaurants/new.html.erb
<h1>New Restaurant</h1>
<%= render "form", restaurant: @restaurant %>

app/views/restaurants/show.html.erb
<h1><%= @restaurant.name %></h1>
<p><strong>Category:</strong> <%= @restaurant.category.capitalize %></p>
<p><strong>Address:</strong> <%= @restaurant.address %></p>

<hr>

<h2>Comments</h2>
<% if @restaurant.reviews.any? %>
  <% @restaurant.reviews.each do |rev| %>
    <div class="mb-3">
      <strong><%= "★" * rev.rating %></strong>
      <p><%= rev.content %></p>
    </div>
  <% end %>
<% else %>
  <p>No Comments Yet.</p>
<% end %>

<hr>

<h3>Add Comment</h3>
<%= simple_form_for [@restaurant, @review] do |f| %>
  <%= f.input :rating, as: :integer, input_html: { min: 0, max: 5 } %>
  <%= f.input :content %>
  <%= f.button :submit, "Send", class: "btn btn-primary mt-2" %>
<% end %>